Fix broken tag page header layout on mobile
faktaoklimatu/web-core pull request #39
Opened 2021-03-10 17:02 UTC by mgrabovsky

Fixes #38

2021-03-10 17:21 UTC, mgrabovsky commented
Note: I did not test this as I'm currently unable to run the build locally.

2021-03-11 21:32 UTC, mukrop requested changes
Does not work:
`Error: no mixin named media-breakpoint-up on line 55:10`

I'd prefer you to debug that, since I don't know breakpoint-up (I'd appreciate a short intro from you sometime).

2021-03-12 08:34 UTC, mgrabovsky commented
Sorry about that. I've changed the query to the usual `min-width`.

I was following the [documentation](https://getbootstrap.com/docs/4.4/layout/overview/#responsive-breakpoints), but now I realise that we're pulling Bootstrap as CSS only, so Sass mixins are not available.

2021-03-12 21:40 UTC, mukrop approved these changes

2021-03-12 21:40 UTC, merged